### PR TITLE
Upgrade Guzzle to ~6.0

### PR DESCRIPTION
**Pull request by stevenscg**
This PR upgrades the SDK to use Guzzle 6.

I am still exercising these changes with functionality very similar to the examples (`shell.php` and `task.php`), hence the "hold" designation for now.

I am curious how others are using this SDK now or would like to in the future.

My initial use case is seeding vaults in developer and CI environments with secrets similar to the deployed environments.

This will likely be a small standalone application and/or repository (vs being called within another app).  Vault is already installed, configured, and running on the host via configuration management tool.

The examples already in the project do this vault seeding sequence very well for CakePHP apps, but I think there is an opportunity to implement some of this logic on a `Jippi\Vault\Helper` namespace very similar to the Consul SDK and be usable within any app or framework.

A "Seed" helper with some convenience methods fits my current use case well:

```
        $this->reset();

        $this->create();
        $this->unseal();

        $this->Vault->waitFor(['sealed' => false, 'standby' => false]);
        $this->Vault->clear();

        $this->mounts();
```

But there may be a better name or context than "seed" from which to offer these methods.

### CODE REVIEW

**Comment by nerdstein** [comment]
I would love to see this get merged as I am building the Drupal contributed module that connects with Vault. My use case is quite similar to that which is in the examples, but Drupal is running Guzzle 6.2.2 and I won't be able to load the SDK until this gets merged.

**Comment by jippi** [comment]
Hi

I'm not sure why it was on HOLD tbh, i think it should be merged in unless someone got a good reason for it not to be? :)

**Comment by nerdstein** [comment]
@jippi --- I totally agree. Guzzle 6 has been out a while. It would be super helpful to get this merged in.

**Comment by jippi** [comment]
Done, and tagged https://github.com/jippi/vault-php-sdk/releases/tag/2.0.0 :)

**Comment by nerdstein** [comment]
Wow, thank you for doing this so promptly!

**Comment by stevenscg** [comment]
@jippi @nerdstein I had a particular use case that dried up as I was finishing this out, so put it on hold until jippi or I could exercise it a bit. We are still using Vault (and Consul and Nomad, etc), so I expect to get back to using this SDK shortly.

I think the cake tasks might still need to be converted.

**Comment by nerdstein** [comment]
This makes sense...

**Pull request merged**
