### PR TITLE
add 'LIST' command to request

### PR DESCRIPTION
**Pull request by TimoDJatomika**
This is used e.g. in the KV Store. 

See: https://www.vaultproject.io/api/secret/kv/kv-v2.html#list-secrets

### CODE REVIEW

**Review by jippi — APPROVED** [review]

**Comment by jippi** [comment]
Thank you @TimoDJatomika ! :)

**Comment by TimoDJatomika** [comment]
Thanks for the quick response. Do you think it would be a good idea to create a new tag? Because I download your repo via composer. And I don't wanna use the "dev-master" version.

**Comment by jippi** [comment]
Done :) https://github.com/jippi/vault-php-sdk/releases/tag/2.0.1

**Comment by TimoDJatomika** [comment]
Thank youuuu

**Pull request merged**
